# Generated by Django 5.1.3 on 2024-11-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_badge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="description",
        ),
        migrations.AddField(
            model_name="badge",
            name="possede",
            field=models.BooleanField(default=False),
        ),
    ]
