# Generated by Django 5.1.3 on 2024-11-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_badge_description_badge_possede"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dresseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("photo", models.URLField(blank=True, null=True)),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True, related_name="dresseurs", to="blog.badge"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="dresseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemons",
                to="blog.dresseur",
            ),
        ),
    ]
