# Generated by Django 5.1.3 on 2024-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_dresseur_character_dresseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
